apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # No auth specified - uses the default credentials from the environment
      # This will use the node's IAM role since IRSA/OIDC is disabled
