apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  # AWS ElastiCache Redis password (if AUTH is enabled)
  # Leave empty if AUTH is not enabled
  password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  # AWS RDS PostgreSQL credentials
  username: "postgres"
  password: "your-secure-password"
